default_stages: [pre-commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        args: ['--tab-width', '2', '--single-quote']
        exclude: '\.(js|jsx|ts|tsx|scss|css|html)$'

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.35.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
